import { type NextPage } from "next";
import Head from "next/head";
import PostList from "~/components/PostList";
import SearchBar from "~/components/SearchBar";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Simple Search</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center gap-10 p-6">
        <SearchBar />
        <PostList />
      </main>
    </>
  );
};

export default Home;
