import { type NextPage } from "next";
import Head from "next/head";
import PostList from "~/components/PostList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Simple Search</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center gap-10 p-6">
        <PostList posts={[]} />
      </main>
    </>
  );
};

export default Home;
